package com.example.greenshadowbackend.enums;

public enum Designation {
    MANAGER,
    SENIOR_ASSISTANT_MANAGER,
    ASSISTANT_MANAGER,
    ADMIN_AND_HR_STAFF,
    OFFICE_ASSISTANT,
    SENIOR_AGRONOMIST,
    AGRONOMIST,
    SOIL_SCIENTIST,
    SENIOR_TECHNICIAN,
    TECHNICIAN,
    SUPERVISORS,
    LABORS
}
